runtime: php55

handlers:
- url: /styles
  static_dir: styles
  
- url: /(.*\.(svg|gif|png|jpg))
  mime_type: image/png
  static_files: assets/img/\1
  upload: assets/img/(.*\.(gif|png|jpg))
  
- url: /.*
  script: index.php