runtime: php8.0.7 # Replace with php74 to use PHP 7.4
api_version: 1
threadsafe: true
# handlers:
# # Serve a directory as a static resource.
# - url: /stylesheets
#   static_dir: stylesheets


# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
- url: /.*
  script: index.php